### ISSUE TITLE
Nomination for Bryan Behrenshausen's "Ambassadorizationing" (to quote Elvis)

### ISSUE THREAD

**Issue by HeidiHVL** [open-organization/governance#11]
Dear Ambassador community,

I propose that @semioticrobotic be “ambassadorized”. 
        
In the past, he was a full-time community architect (when Marketing Communications was the community sponsor at Red Hat) but now community architect is only part of his role (about half-time, these days, since we’re sponsored by the Open Source Program Office). 

Yet, he spends a lot of time helping us publish and create materials and do lots of other important things --- and I’d bet a bunch of it is his free time. 

His contributions to the community are too numerous to list but they include consistently editing and contributing his wisdom and awesomeness to our publications, managing the pipeline of activity, identifying new projects, holding microphones, editing audio files, advising me to not make career-limiting moves, and more.... 

Bryan deserves recognition as an Ambassador in the community and among us, and it's long overdue. Long live Dr. Mr. Ambassador Bryan Behrenshausen! 

Please respond with your support for this proposal! I need two "Hip Hip Hooray's" for this proposal to be approved.
Thanks in advance, 
Heidi

**Comment by funnelfiasco** [comment]
+1

**Comment by jenkelchner** [comment]
I wholeheartedly support @semioticrobotic finally getting his due and honor for his part in this crazy cirus of ours <3

+1

**Comment by semioticrobotic** [comment]
Thank you all. :pray: As per [guidelines in our governance documents](https://github.com/open-organization/governance/wiki/Community-Roles), this issue will remain open to discussion and debate for one week. Making a note to revisit on 2020.08.20.

**Comment by samuelknuth** [comment]
+1

**Comment by jimmysjolund** [comment]
I have always considered Bryan as the leader of the Ambassadors which I suppose would make him the President. In lack of President roles I fully support the nomination for Ambassador.

**Comment by HeidiHVL** [comment]
Well... it's been a week so it looks like you, @semioticrobotic, might be officially Ambassadorized!

**Comment by semioticrobotic** [comment]
That's four votes in favor and none opposed, for a [net total of four](https://github.com/open-organization/governance/wiki/Community-Roles).

Thank you all so much. I appreciate it. :pray: 

And I do promise to uphold [the honor and dignity])https://media.giphy.com/media/8oe1ekRC6kjPq/giphy.gif) the position commands.

Incidentally, I'm working on a [new community roster](https://github.com/open-organization/governance/blob/9e33fd2273f9db699ee42773d1f6e91ac9b566ff/community-roster.md) and [welcome feedback on it](https://github.com/open-organization/governance/pull/12). I will of course be adding my own name. :partying_face:
