### ISSUE TITLE
Nominating Jos Groen as Ambassador

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/governance#13]
I would like to propose that contributor @JosGroenNL become an Open Organization Ambassador. I offer the following in support of this nomination:

- Jos has been [thinking and writing](https://opensource.com/users/jos-groen) about open organizations and open leadership for quite some time, and in June he published some of his work in [our channel on Opensource.com](https://opensource.com/open-organization/20/6/organization-everyone-deserves). As Jos continues to write, I would very much like to see his voice among those we feature and amplify.
- Jos is also a seasoned speaker on the above topics. In July, he [presented a webinar](https://www.redhat.com/en/events/webinar/how-to-drive-the-transformation-journey-through-an-open-organization-approach-2020) entitled "How to drive the transformation journey through an open organization approach." Jos could assist our community's efforts to develop additional presentation materials and workshop offerings.
- Jos recently contributed [a new chapter](https://github.com/open-organization/open-org-leaders-manual/blob/master/groen-transformation-leadership-hybrid-world.md), "Transformation and Leadership in a Hybrid World," to *The Open Organization Leaders Manual* and has been an outspoken advocate for the book, especially on social media.
- Jos is a prolific and well-connected LinkedIn user who uses the platform to engage with others on open organization topics. He has [volunteered](https://www.theopenorganization.community/t/november-12-2020-meeting/172) to join our community's efforts to explore LinkedIn as a platform for community building, and would be a true asset to the work.

I hope others will consider supporting this nomination.

## Next steps

A reminder about procedures, as outlined in our governance documents:

> The community will discuss the nomination for a period of no more than one week after the issue is filed. During that time, current Ambassadors can offer their support for the nomination or raise objections to it.
> 
> A nomination receiving "net-positive" support from at least two non-nominating Ambassadors is approved. This means that:
>
> - if a nomination receives approval from two Ambassadors, it is approved  
> - if a nomination receives approval from three Ambassadors, and an objection from one, it is approved  
> and so on
>
> Ambassadors pledge a minimum commitment of one year. At the conclusion of their respective terms, ambassadors will discuss plans to renew or complete their commitments.

**Comment by samuelknuth** [comment]
I second this.

**Comment by JosGroenNL** [comment]
Thank you for the nomination. I'd like to contribute and call out to other leaders in the world to consider the open organization as a durable alternative for the current classic and conservative way of leading businesses. I can help with linked in and contribute in writing and creating more articles and content in this community.

**Comment by lbm-a** [comment]
Hopefully I'm allowed to pitch in as someone that directly benefits from and is part of Jos' open organization.
I've been a developer with Axians for over a year and half. A couple of keywords to sum up my time working with Jos so far: transparent, empowering, purposeful and determined.
I wholeheartedly support this nomination.

**Comment by semioticrobotic** [comment]
Endorsements can never hurt! Thanks, @lbm-a.

**Comment by engineerteacher** [comment]
I hereby support this nomination and vote that Jos Groen be named an Open Organization Ambassador.

**Comment by RonMcFarland** [comment]
I too would like to endorse Jos Groen as an Open Organization Ambassador.  Looking forward to working with him.

**Comment by semioticrobotic** [comment]
Well, the requisite voting period has passed, and I count three votes in favor of the nomination—which means @JosGroenNL is now an Open Organization Ambassador. Congratulations, Jos! I'll be connecting with you via email with some additional instructions and pointers.

**Comment by HeidiHVL** [comment]
oh good @semioticrobotic because I just went to concur and saw it was closed - wooo congrats @JosGroenNL!

**Comment by JosGroenNL** [comment]
Well, thank you all! Open is the future

Met vriendelijke groet,

Jos Groen
