### ISSUE TITLE
Update our purpose statement for 2021

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/governance#14]
**Current:** 
(thoughts: sounds academic. But we are practitioners)
The Open Organization is a community-driven project dedicated to exploring how open principles change the ways we work, manage, and lead.

Our community members study and share strategies for building organizational cultures on principles like transparency, adaptability, collaboration, inclusivity, and community.

Suggestions:
"The Open Organization is a community-driven project driving the global conversation on how open principles can change the ways we work, manage, and lead."

"The how is more around driving communities and sharing knowledge and experiences"

**Comment by LauraHilliger** [comment]
@jenkelchner mentioned the way people misinterpret the word "facilitation" to mean "workshop facilitation" which has often been my experience as well. So just noting that here

**Comment by semioticrobotic** [comment]
As per above, I've worked on #20 to incorporate these changes into the project's framing documents. Please have a look!
