### ISSUE TITLE
Update our commitments for 2021

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/governance#15]
### Current
**Learning**. We're researching open source values so we can better understand how they're influencing today's innovative organizational cultures, and we're always refining the "open organization" concept, differentiating or distinguishing it from seemingly similar approaches to management and leadership.
**Helping**. We're a trusted resource for anyone interested in leveraging the power of open principles to improve their organizations.
**Translating**. We explain community-specific vocabularies to general audiences seeking to understand the benefits of an open approach to management and leadership.
**Engaging**. We draw others into productive dialogues and exploratory activities that illuminate the benefits of applying open thinking to organizational contexts.

### thoughts:
Attached to #14 - maybe rearranging and or adding "sharing"
Helping = Sharing in the context we have

**Comment by LauraHilliger** [comment]
Ben - Enable? I also like catalyst. :)
Jen: I don't use enable... I use empower.  Enable still has a dependency with it.

**Comment by semioticrobotic** [comment]
As per above, I've worked on #20 to incorporate these changes into the project's framing documents. Please have a look!
