### ISSUE TITLE
Update our methods for 2021

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/governance#16]
### Current

**Publishing** articles, books, and other resources exploring the nature of openness in contemporary organizations
**Exhibiting** and speaking at industry and community-focused events
**Connecting** with and interviewing innovative leaders, managers, and practitioners innovating in an open manner
**Maintaining** a repository of high-quality, immediately accessible, vetted resources anyone can use to implement open principles in their teams or organizations

Suggestions:
Jos - learning forward
Jen - I agree with Jos... expanding awareness is really what we do right?  And foster relationships
Co-create?
Expand awareness +1

relates to #14 and #15

**Comment by semioticrobotic** [comment]
As per above, I've worked on #20 to incorporate these changes into the project's framing documents. Please have a look!
