### ISSUE TITLE
Find out the precident for Youtube Re the OSPO

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/governance#17]
We would like an Open Org Project Youtube channel. OSPO probably has a precident :)

**Comment by semioticrobotic** [comment]
Further updates as events warrant!

**Comment by semioticrobotic** [comment]
Events now warrant!

We are free to create a channel as we see fit. I have finer guidelines related to, e.g., branding and infosec, but I will spare those here and share them in more detail with the crew volunteering to spin this up.

So, next step will be for me to create a YouTube channel and get admins onboarded. I will do that in the next day or two, so please watch your inboxes!

**Comment by semioticrobotic** [comment]
Oh, and one more thing: We also have immediately available resources for creating and deploying custom video bumpers, which I am also engaging so we can launch as quickly as possible. Will report on that soon, too.

**Comment by semioticrobotic** [comment]
I think I'm comfortable closing this now, as we seem to have the information and direction we needed to get started.
