### ISSUE TITLE
Pin most used repos in Open Org github profile

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/governance#19]
I'm not an admin of our open-organization Github profile, so I can't do this myself, but I think we should pin Governance and the Editorial Repos to the top of our org page. Governance holds all the project to-dos and Editorial holds all the content to-dos - I think both are the most relevant to all ambassadors and many contributors as well. Will just make stuff to find.

**Comment by semioticrobotic** [comment]
Done and done! Thanks, @LauraHilliger! This is a great suggestion.
