### ISSUE TITLE
Documented Ambassador writing expectations don't reflect reality

### ISSUE THREAD

**Issue by funnelfiasco** [open-organization/governance#2]
The [current doc](https://opensource.com/open-organization/resources/ambassadors-program) says, re: writing articles

>  typically one every month

I don't know that any of us are contributing that frequently, and certainly the editorial calendar can't accommodate that level of productivity. So what is a more reasonable expectation?

**Comment by semioticrobotic** [comment]
You're absolutely correct, @funnelfiasco, and as a matter of fact addressing 2019 updates to the program description was on my to-do list for the week. So I hope to have more on this front soon. In the meantime, however, this is a great place to host a discussion about what folks think are more appropriate and manageable expectations.

**Comment by semioticrobotic** [comment]
I've [merged an update to the description](https://github.com/open-organization-ambassadors/ambassador-program-description/pull/3) and will propagate it. Naturally we're always welcome to revive this thread when we're ready to modify the description again.
