### ISSUE TITLE
Please invite me to the open-organisation community

### ISSUE THREAD

**Issue by shashank2906** [open-organization/governance#22]
Hello everybody , I am shashank
I learnt about open-organisation through github .
I want to join the organisations and make open source contributions that would help me excel in my skills and would also help me to get mentorship and grow with the community .

Thank you
Waiting to join the community soon

**Comment by semioticrobotic** [comment]
Greetings, @shashank2906! I'm so glad you found us. Thanks for reaching out and connecting with us.

We're certainly delighted to hear you'd like to contribute to the Open Organization project and community. What kinds of contributions would you like to make most? I can direct you to the person or group working in those areas so you can get started. For example, we always need help:

- Writing and editing articles
- Interviewing experts and collecting case studies
- Editing books and whitepapers
- Managing our website

... and so on.

You can see open issues in our various repositories. Have a look and see what you'd like to do!

**Comment by shashank2906** [comment]
Thanks for the reply 
I am interested in writing and editing tech articles and can also help with the technical issues regarding website .
I am an undergrad studying computer's and mathematics so i can help the community according to my abilities in writing and editing articles and also with development and maintenance of the website

Thank you.

**Comment by semioticrobotic** [comment]
Okay! Thanks. Welcome!

**Comment by shashank2906** [comment]
How can i proceed further ?

**Comment by semioticrobotic** [comment]
Thanks for asking! The first thing you'll likely want to do is introduce yourself at [the community hub](http://theopenorganization.community)! There you can also meet other community members and learn more about projects in progress.

We're a largely non-technical community, so the articles we write and publish tend to pertain more to the "people and process" side of open organizational culture and design. But it's nice to know you're here to help us confirm technical details in the event that an article involves those.

As for the website: this is a nice time to be jumping in! @LauraHilliger and I have been tinkering with [a website refresh](https://github.com/open-organization/new-website). We haven't started filing issues just yet, but when we do we will assign some of tyhe more technical bits to you! Meanwhile, you can see our [test site](https://theopenorganization.org/new-website).

**Comment by shashank2906** [comment]
Thank you so much .

**Comment by semioticrobotic** [comment]
Because you've received your invitation, I'll close this issue. Welcome, @shashank2906!
