### ISSUE TITLE
Moving community resources to new GitHub organization

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/governance#7]
The incredibly generous @MarkusTiede has graciously offered our community the use of <[github.com/open-organization](https://github.com/open-organization)> as we continue evolving the Open Organization community's brand and scope. I'd like us to consider the offer, and wanted to open this space for community discussion.

This would mean moving resources from the ``open-organization-ambassadors`` collection of repositories to the ``open-organization`` collection of repositories, and operating that GitHub organization as our new community home. This would also be the repository from which we'd host and serve the new Open Organization project website.

We'd then discontinue use of the ``open-organization-ambassadors`` repositories. All Open Organization Ambassadors would automatically regain member-level access to all project repositories when we'd made the move.

I believe this move would be a positive and useful one for our community but did not want to undertake something this significant without at least observing a comments and discussion period. So let's please discuss!

I'll plan to revisit this decision in a week and move ahead unless I see stringent objections here.

**Comment by MarkusTiede** [comment]
Hi all (thanks @semioticrobotic for this "chorus of praise" ☺️ 😅) - I hope you're all doing ok atm!

I'd love to give this to a broader audience / community: and maybe we could get / stay in touch within the organization.

And as always: supporting (https://github.com/sponsors/MarkusTiede/) each other is welcome at any time!

**Comment by semioticrobotic** [comment]
Hearing no objections, I'll begin preparations for a transition in a day or two. @MarkusTiede: apologies in advance for the moving boxes scattered everywhere.

**Comment by semioticrobotic** [comment]
Okay! I *think* I was able to facilitate the move with surprisingly little turbulence. Once again, a round of collective thanks to @MarkusTiede for letting us crash. I think these new digs suit us.

**Comment by semioticrobotic** [comment]
Welcome, all! And one final shout-our to @MarkusTiede! :clinking_glasses:
